### ISSUE TITLE
Add '/project/:project_id/archive' endpoint to archive to s3

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/track-changes-sharelatex#5]
This is similar to the work done on the docstore https://github.com/sharelatex/docstore-sharelatex/pull/8

a request to this endpoint will take the data out of mongo and store it into s3. If required a marker may be needed to be left in mongo saying there is data. For docstore the doc lines are replaces with inS3:true so something similar for track changes would work, but this is under the assumption that removing the rest of the data in the mongo doc will save us a lot of data.

If a standard request is made to get some changes or add new ones in then the system should automatically restore the data from s3 and act as normal. 

questions:

- where to add this data layer?
- how will track changes know if there is data in s3 which can be restored?
- ShareLaTeX docs have many track changes mongo docs, is it better to delete the docs in mongo after archive in s3, then elsewhere in a different collection (track-changes-archive-something) store {project_id:123, doc_id:456, inS3:true}

**Comment by briangough** [comment]
> ShareLaTeX docs have many track changes mongo docs, is it better to delete the docs in mongo after archive in s3, then elsewhere in a different collection (track-changes-archive-something) store {project_id:123, doc_id:456, inS3:true}

I think we should delete the entries from the docHistory collection and leave a single stub.  

The big issue with docHistory has been the number of entries going into the collection, causing a big index.  We have reduced this by packing multiple changes into 1 document, but this only reduces the problem, it doesn't eliminate it.  The collection grows more slowly but it is still growing.  Also we still have the histories of old unused projects.  So it seems better to delete everything.

If we do that, there are two scenarios we need to consider.  

  1. Someone edits an archived project, putting new entries into docHistory
  2. Someone views the history of an archived project.

For efficiency we only want to pull down the changes when someone views the history the archived project.  People do not look at the history very often.


Important: one thing we need to handle is that when someone edits a document and causes changes to be sent to track-changes, we do a check of the last version stored in docHistory to make sure that newVersion = oldVersion + 1.

It's important to preserve this check when the document is archived, as a bad/missing/duplicate version entry will break the history!  We don't want to pull down the full history to do that, so we should keep that version information around.   We only want to pull down the full history when someone actually tries to look at it.

The relevant code is UpdatesManager.coffee compressAndSaveRawUpdates which calls MongoManager.coffee getLastCompressedUpdate.

As part of the check the changes are combined if the new edit joins immediately onto the previous one (e.g. edit 1 = "hello"  edit 2 = " world").   But the combining of edits is not crucial, since it's just there to reduce the number of entries, so there won't be a big overhead if the first entry after an archive skips creates a new entry -- as long as we have checked the version.

The history can be big, we don't necessarily want to send the whole thing to S3 in one file.

I've used bulk updates for the packing of docHistory and they worked well.  But you may hit memory issues from trying to archive the whole document history, as some projects have very big histories (where they cut and paste the whole file repeatedly, causing massive diffs).  One option would be to stream the entries to a file and then upload that to s3.   For packing I had to do it incrementally, where I just took changes in groups < 1MB.

**Comment by briangough** [comment]
Archiving has now been added.
